// Code generated by ent, DO NOT EDIT.

package ent

import (
	"blog-go/ent/hitokoto"
	"blog-go/ent/predicate"
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// HitokotoDelete is the builder for deleting a Hitokoto entity.
type HitokotoDelete struct {
	config
	hooks    []Hook
	mutation *HitokotoMutation
}

// Where appends a list predicates to the HitokotoDelete builder.
func (hd *HitokotoDelete) Where(ps ...predicate.Hitokoto) *HitokotoDelete {
	hd.mutation.Where(ps...)
	return hd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (hd *HitokotoDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, hd.sqlExec, hd.mutation, hd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (hd *HitokotoDelete) ExecX(ctx context.Context) int {
	n, err := hd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (hd *HitokotoDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(hitokoto.Table, sqlgraph.NewFieldSpec(hitokoto.FieldID, field.TypeInt))
	if ps := hd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, hd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	hd.mutation.done = true
	return affected, err
}

// HitokotoDeleteOne is the builder for deleting a single Hitokoto entity.
type HitokotoDeleteOne struct {
	hd *HitokotoDelete
}

// Where appends a list predicates to the HitokotoDelete builder.
func (hdo *HitokotoDeleteOne) Where(ps ...predicate.Hitokoto) *HitokotoDeleteOne {
	hdo.hd.mutation.Where(ps...)
	return hdo
}

// Exec executes the deletion query.
func (hdo *HitokotoDeleteOne) Exec(ctx context.Context) error {
	n, err := hdo.hd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{hitokoto.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (hdo *HitokotoDeleteOne) ExecX(ctx context.Context) {
	if err := hdo.Exec(ctx); err != nil {
		panic(err)
	}
}
