// Code generated by ent, DO NOT EDIT.

package ent

import (
	"blog-go/ent/hitokoto"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// Hitokoto is the model entity for the Hitokoto schema.
type Hitokoto struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Content holds the value of the "content" field.
	Content string `json:"content,omitempty"`
	// Source holds the value of the "source" field.
	Source string `json:"source,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt    time.Time `json:"updated_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Hitokoto) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case hitokoto.FieldID:
			values[i] = new(sql.NullInt64)
		case hitokoto.FieldContent, hitokoto.FieldSource:
			values[i] = new(sql.NullString)
		case hitokoto.FieldCreatedAt, hitokoto.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Hitokoto fields.
func (h *Hitokoto) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case hitokoto.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			h.ID = int(value.Int64)
		case hitokoto.FieldContent:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field content", values[i])
			} else if value.Valid {
				h.Content = value.String
			}
		case hitokoto.FieldSource:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field source", values[i])
			} else if value.Valid {
				h.Source = value.String
			}
		case hitokoto.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				h.CreatedAt = value.Time
			}
		case hitokoto.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				h.UpdatedAt = value.Time
			}
		default:
			h.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Hitokoto.
// This includes values selected through modifiers, order, etc.
func (h *Hitokoto) Value(name string) (ent.Value, error) {
	return h.selectValues.Get(name)
}

// Update returns a builder for updating this Hitokoto.
// Note that you need to call Hitokoto.Unwrap() before calling this method if this Hitokoto
// was returned from a transaction, and the transaction was committed or rolled back.
func (h *Hitokoto) Update() *HitokotoUpdateOne {
	return NewHitokotoClient(h.config).UpdateOne(h)
}

// Unwrap unwraps the Hitokoto entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (h *Hitokoto) Unwrap() *Hitokoto {
	_tx, ok := h.config.driver.(*txDriver)
	if !ok {
		panic("ent: Hitokoto is not a transactional entity")
	}
	h.config.driver = _tx.drv
	return h
}

// String implements the fmt.Stringer.
func (h *Hitokoto) String() string {
	var builder strings.Builder
	builder.WriteString("Hitokoto(")
	builder.WriteString(fmt.Sprintf("id=%v, ", h.ID))
	builder.WriteString("content=")
	builder.WriteString(h.Content)
	builder.WriteString(", ")
	builder.WriteString("source=")
	builder.WriteString(h.Source)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(h.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(h.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Hitokotos is a parsable slice of Hitokoto.
type Hitokotos []*Hitokoto
