// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Book is the predicate function for book builders.
type Book func(*sql.Selector)

// Collection is the predicate function for collection builders.
type Collection func(*sql.Selector)

// Comment is the predicate function for comment builders.
type Comment func(*sql.Selector)

// Friend is the predicate function for friend builders.
type Friend func(*sql.Selector)

// Hitokoto is the predicate function for hitokoto builders.
type Hitokoto func(*sql.Selector)

// Image is the predicate function for image builders.
type Image func(*sql.Selector)

// Post is the predicate function for post builders.
type Post func(*sql.Selector)

// Tag is the predicate function for tag builders.
type Tag func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
